version: 1.0
prefix: "&e[hc] "
settings:
  permanent-deathban: true
  deathban-duration: 30 # Duration in minutes
  grace-period: 5 # Duration in minutes


discord-webhook:
    url: "https://discord.com/api/webhooks/your-webhook-url"
    server-name: "Hardcore Minecraft Server"
    ping-role-id: "123456789012345678"
    notify-on:
      manual-deathban:
        enabled: true
        ping-role: false
      automatic-deathban:
        enabled: true
        ping-role: true
      revive:
        enabled: true
        ping-role: false