version: 1.0 # Do not change this value, it will update automatically
prefix: "&e[hc] "
settings:
  permanent-deathban: true
  deathban-duration: 30 # Duration in minutes
  grace-period: 5 # Duration in minutes

sounds:
  # Wants a list of all available sounds? Check https://www.digminecraft.com/lists/sound_list_pc.php
  deathban-sound:
    sound: ENTITY_WITHER_SPAWN
    enabled: true
  revive-sound:
    sound: ENTITY_PLAYER_LEVELUP
    enabled: true

velocity-module:
    enabled: false
    server-to-send: ""
    commands-to-execute:
      - "msg {player} You have been deathbanned"
luckperms-module:
  enabled: false
  deathbanned-has-permission: "hardcore.deathbanned"
  grace-period-has-permission: "hardcore.ingraceperiod"

discord-webhook:
    url: "https://discord.com/api/webhooks/your-webhook-url"
    server-name: "Hardcore Minecraft Server" # Replace with your server name, Handy for networks
    ping-role-id: "123456789012345678" # Replace with your Discord role ID to ping
    notify-on:
      manual-deathban:
        enabled: true
        ping-role: false
      automatic-deathban:
        enabled: true
        ping-role: true
      permanent-deathban:
        enabled: true
        ping-role: true
      config-reload:
        enabled: true
        ping-role: true
      grace-remove:
        enabled: true
        ping-role: false
      revive:
        enabled: true
        ping-role: false
